Ui debug
enove/NoSLB pull request #148
Opened 2016-10-27 23:20 UTC by eoghanTadhg

Assorted user interface fixes including general and Work section debugging.

2016-10-27 23:26 UTC, micchickenburger commented on packages/thriver-core/lib/client/scroll.js
> +            if(document.getElementById("back-to-top"))
Why is this condition needed?

2016-10-27 23:31 UTC, eoghanTadhg commented on packages/thriver-core/lib/client/scroll.js
> +            if(document.getElementById("back-to-top"))
It seems it was causing error if the element did not exist. Will investigate why it does not exist.

2016-10-27 23:57 UTC, micchickenburger requested changes

2016-10-27 23:57 UTC, micchickenburger commented on packages/thriver-navigation/lib/templates/utility.html
> +        <a href="{{#if equals type 'link'}}{{{url}}}{{/if}}{{#if equals type 'sidebar'}}/{{{sidebar}}}{{/if}}{{#if equals type 'null'}}/{{/if}}" target="{{#if equals type 'external'}}_blank{{/if}}" c
Can this be made more readable?

2016-10-27 23:57 UTC, micchickenburger commented on packages/wcasa:work/lib/client/work.js
> +    // TODO: Use smoothScroll
New syntax for TODOs:

`// TODO(eoghantadhg): Use smoothscroll`

2016-10-27 23:57 UTC, micchickenburger commented on packages/wcasa:work/lib/client/work.js
> +    //Scroll to top of work on change tabs
We now use airbnb's style guide.  Spaces are required after slashes:

`// Scroll to...`

2016-10-27 23:57 UTC, micchickenburger commented on packages/wcasa:work/lib/client/work.js
> +        offset = $('[id="what-we-do"]').offset().top + 228;
Create a constant for value `228`, like:  `const OFFSET = 228;`

2016-10-27 23:57 UTC, micchickenburger commented on packages/wcasa:work/lib/client/work.js
> +        $('body').animate({ scrollTop: offset }, 750);
Create a constant here, too.

2016-11-14 02:48 UTC, eoghanTadhg commented
These changes have been absorbed by branch `wcasa-dev` via an alternative pull-request, `mobileUiDebug`.

2016-11-14 02:48 UTC, closed without merging