Work img align
enove/NoSLB pull request #178
Opened 2016-11-17 04:56 UTC by eoghanTadhg

Moved markdown `img` styles out of work and into `type.import.less`.
Now images within an ancestor: `.markdown` can utilize the `alt` tag alignment feature.

- `alt="Left:...` will return left aligned
- `alt="Right:...` will return right aligned
- `alt="Center:..` will return center aligned

Default behaviors remain:

- Left aligned with no text-wrap
-Max-width of 100%

NOTE: These will not work on `img` elements which are placed alone within a `p` element.

2016-11-19 20:31 UTC, micchickenburger requested changes

2016-11-19 20:31 UTC, micchickenburger commented on packages/thriver-core-styles/lib/styles/type.import.less
> +// @import "../index.less";
Since this is commented code, it should just be deleted.

2016-11-21 17:31 UTC, eoghanTadhg commented
@micchickenburger , The line of code has been removed and this branch is ready to merge.

2016-11-22 05:30 UTC, micchickenburger approved these changes

2016-11-22 05:31 UTC, merged