Feature account create alert
enove/NoSLB pull request #301
Opened 2017-07-09 02:36 UTC by eoghanTadhg

@micchickenburger : may need some help at the appropriate way to write the timeout function to close on line 19 of `thriver-core/lib/client/alerts.js`

2017-09-17 18:32 UTC, eoghanTadhg commented
@micchickenburger , need help resolving these travis-ci fails. Not sure what I'm doing wrong here.

2018-01-04 18:05 UTC, eoghanTadhg commented
@micchickenburger , This works as expected, but I am unable to pass the Travis CI build, even after making what I thought were the fixes. Can you look into this? Once what ever the semantic issue is resolved, this is working and good to go.

2018-01-21 17:40 UTC, micchickenburger requested changes

2018-01-21 17:40 UTC, micchickenburger commented on packages/thriver-core/lib/templates/canvas.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
Accidental duplication of the script being loaded on line 39?

2018-01-21 17:40 UTC, micchickenburger commented on packages/thriver-core/lib/templates/canvas.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
Also, why do we have this at all?  Doesn't Meteor take care of shivs for old browsers?

2018-01-21 17:40 UTC, micchickenburger commented on packages/thriver-core-components/lib/component-alert/alerts.less
>  }
All files must end with a newline.

2018-01-21 17:40 UTC, micchickenburger commented on packages/thriver-core/lib/client/alerts.js
> +    alert.classList.add('active', opts.class);
Is there a class for notifs that aren't "positive?"  Like for error messages?

2018-01-21 17:40 UTC, micchickenburger commented on packages/thriver-core/lib/client/alerts.js
> +    $(alert).find('.content').html(opts.content);
We should not update html here, since that could potentially open us up for a XSS attack.  We should used textContent instead.

2018-11-14 18:23 UTC, eoghanTadhg commented
This branch is dated and alerts will be built as toasts in a new branch.

2018-11-14 18:23 UTC, closed without merging